# Generated by Django 3.2 on 2021-05-18 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0003_alter_works_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='like',
            field=models.ManyToManyField(related_name='work_one', to=settings.AUTH_USER_MODEL),
        ),
    ]
