# Generated by Django 3.2 on 2021-05-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0004_works_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bill_number',
            field=models.IntegerField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
