# Generated by Django 3.2 on 2021-06-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0009_alter_customuser_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='background-user_image'),
        ),
    ]
