# Generated by Django 3.2 on 2021-06-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0011_alter_customuser_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bill_number',
            field=models.IntegerField(blank=True, max_length=16, null=True),
        ),
    ]
